# fly.toml app configuration file generated for blood-sphere-bot on 2023-08-27T16:02:19+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blood-sphere-bot"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[deploy]
  release_command = "python app.py"